# Generated by Django 5.2.6 on 2025-12-21 20:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteCalculatorConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_rate_per_mile",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.50"),
                        help_text="Base cost per mile",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "service_multipliers",
                    models.JSONField(
                        default=dict,
                        help_text="Service type multipliers in JSON format, e.g. {'RESIDENTIAL_MOVING': 1.5, 'OFFICE_RELOCATION': 2.0}",
                    ),
                ),
                (
                    "weight_factor",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0015"),
                        help_text="Cost per pound of cargo",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                (
                    "minimum_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="Minimum quote amount",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.00"))
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calculator_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote Calculator Configuration",
                "verbose_name_plural": "Quote Calculator Configuration",
            },
        ),
    ]
