# Generated by Django 5.2.6 on 2025-10-03 11:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("RESIDENTIAL_MOVING", "Residential Moving"),
                            ("OFFICE_RELOCATION", "Office Relocation"),
                            ("PALLET_DELIVERY", "Pallet Delivery"),
                            ("SMALL_DELIVERIES", "Small Deliveries"),
                        ],
                        default="SMALL_DELIVERIES",
                        max_length=50,
                    ),
                ),
                ("cargo_description", models.TextField()),
                ("pickup_address", models.TextField()),
                ("pickup_city", models.CharField(max_length=100)),
                ("pickup_contact_person", models.CharField(max_length=100)),
                ("pickup_contact_phone", models.CharField(max_length=20)),
                ("delivery_address", models.TextField()),
                ("delivery_city", models.CharField(max_length=100)),
                ("delivery_contact_person", models.CharField(max_length=100)),
                ("delivery_contact_phone", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("requested_pickup_date", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
