# Generated by Django 5.2.6 on 2025-12-18 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_job_proof_of_delivery_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="proof_of_delivery_image",
        ),
    ]
