# Generated by Django 5.2.6 on 2025-12-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_job_proof_of_delivery_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_number",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
    ]
