# Generated by Django 5.2.6 on 2025-10-03 11:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent"),
                            ("PAID", "Paid"),
                            ("VOID", "Void"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("NOT_PAID", "Not Paid"),
                            ("STRIPE", "Stripe"),
                            ("PAYPAL", "PayPal"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CARD", "Card (Manual)"),
                            ("CHEQUE", "Cheque"),
                        ],
                        default="NOT_PAID",
                        max_length=20,
                    ),
                ),
                (
                    "payment_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for manual payments (e.g., cheque number, transaction ID).",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
