var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/orders/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__88f710e2._.js")
R.c("server/chunks/ssr/_472c1382._.js")
R.c("server/chunks/ssr/_2ccdcc02._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5a1970a6._.js")
R.c("server/chunks/ssr/node_modules_next_dist_07951b80._.js")
R.c("server/chunks/ssr/node_modules_next_dist_81959fb0._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/app_layout_tsx_565cb814._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_dashboard_layout_tsx_12b56d5a._.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_orders_page_actions_1ee39fb7.js")
R.m(13318)
module.exports=R.m(13318).exports
